services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.acmeresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.acmeresolver.acme.email=khutwah-production@rockybars.com'
      - '--certificatesresolvers.acmeresolver.acme.storage=/letsencrypt/acme.json'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - 'letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock'
  staging:
    image: staging-image
    environment:
      - 'NEXT_PUBLIC_SKIP_MUMTAZ_LOGIN=true'
      - 'DOTENV=/run/secrets/staging-secret'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.staging.rule=Host(`mh-staging.khutwah.id`)'
      - 'traefik.http.routers.staging.entrypoints=websecure'
      - 'traefik.http.routers.staging.tls.certresolver=acmeresolver'
    deploy:
      replicas: 1
      update_config:
        order: start-first
volumes:
  letsencrypt:

secrets:
  staging-secret:
    external: true
