primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[statics]]
  guest_path = '/app/.next/static'
  url_prefix = '/_next/static'

[http_service.http_options.response.headers]
  X-Nextjs-Cache = false
  X-Nextjs-Prerender = false
  X-Nextjs-Stale-Time = false
  X-Powered-By = false

[env]
  NEXT_PUBLIC_SKIP_MUMTAZ_LOGIN = 'true'
  STUDENTS_DEFAULT_PASSWORD = 'test123'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  strategy = "immediate"
