primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[statics]]
  guest_path = '/app/.next/static'
  url_prefix = '/_next/static'

[env]
  NEXT_PUBLIC_SKIP_MUMTAZ_LOGIN = 'true'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
