import plugin from "tailwindcss/plugin";

export const typographyPlugin = plugin(function ({ addUtilities }) {
  addUtilities({
    ".mtmh-display-large": {
      "font-size": "36px",
      "font-weight": "700",
      "line-height": "44px",
      "text-align": "left",
      "text-underline-position": "from-font",
      "text-decoration-skip-ink": "none",
    },
    ".mtmh-display-medium": {
      "font-size": "32px",
      "font-weight": "700",
      "line-height": "40px",
      "text-align": "left",
      "text-underline-position": "from-font",
      "text-decoration-skip-ink": "none",
    },
    ".mtmh-display-small": {
      "font-size": "28px",
      "font-weight": "600",
      "line-height": "36px",
      "text-align": "left",
      "text-underline-position": "from-font",
      "text-decoration-skip-ink": "none",
    },
    ".mtmh-heading-h1": {
      "font-size": "28px",
      "font-weight": "700",
      "line-height": "36px",
      "text-align": "left",
      "text-underline-position": "from-font",
      "text-decoration-skip-ink": "none",
    },
    ".mtmh-heading-h2": {
      "font-size": "24px",
      "font-weight": "600",
      "line-height": "32px",
      "text-align": "left",
      "text-underline-position": "from-font",
      "text-decoration-skip-ink": "none",
    },
    ".mtmh-heading-h3": {
      "font-size": "20px",
      "font-weight": "500",
      "line-height": "28px",
      "text-align": "left",
      "text-underline-position": "from-font",
      "text-decoration-skip-ink": "none",
    },
    ".mtmh-title-large": {
      "font-size": "18px",
      "font-weight": "700",
      "line-height": "24px",
      "text-align": "left",
      "text-underline-position": "from-font",
      "text-decoration-skip-ink": "none",
    },
    ".mtmh-title-medium": {
      "font-size": "16px",
      "font-weight": "600",
      "line-height": "24px",
      "text-align": "left",
      "text-underline-position": "from-font",
      "text-decoration-skip-ink": "none",
    },
    ".mtmh-title-small": {
      "font-size": "14px",
      "font-weight": "500",
      "line-height": "20px",
      "text-align": "left",
      "text-underline-position": "from-font",
      "text-decoration-skip-ink": "none",
    },
    ".mtmh-body-large": {
      "font-size": "20px",
      "font-weight": "400",
      "line-height": "28px",
      "text-align": "left",
      "text-underline-position": "from-font",
      "text-decoration-skip-ink": "none",
    },
    ".mtmh-body-medium": {
      "font-size": "16px",
      "font-weight": "400",
      "line-height": "24px",
      "text-align": "left",
      "text-underline-position": "from-font",
      "text-decoration-skip-ink": "none",
    },
    ".mtmh-body-small": {
      "font-size": "14px",
      "font-weight": "400",
      "line-height": "20px",
      "text-align": "left",
      "text-underline-position": "from-font",
      "text-decoration-skip-ink": "none",
    },
    ".mtmh-button-large": {
      "font-size": "16px",
      "font-weight": "600",
      "line-height": "24px",
      "text-align": "left",
      "text-underline-position": "from-font",
      "text-decoration-skip-ink": "none",
    },
    ".mtmh-button-small": {
      "font-size": "12px",
      "font-weight": "600",
      "line-height": "16px",
      "text-align": "left",
      "text-underline-position": "from-font",
      "text-decoration-skip-ink": "none",
    },
    ".mtmh-label": {
      "font-size": "12px",
      "font-weight": "500",
      "line-height": "16px",
      "text-align": "left",
      "text-underline-position": "from-font",
      "text-decoration-skip-ink": "none",
    },
    ".mtmh-small-text": {
      "font-size": "10px",
      "font-weight": "400",
      "line-height": "14px",
      "text-align": "left",
      "text-underline-position": "from-font",
      "text-decoration-skip-ink": "none",
    },
  });
});
