name: Sanity Check
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Read .nvmrc
        id: node-version
        run: |
          echo "version=`cat .nvmrc`" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ steps.node-version.outputs.version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run format
      - run: npm run sql:format
      - name: Run consistency check
        run: |
          if [ ! -z "`git status -s`" ]; then \
            echo "Following files are not consistent with CI:"; \
            git status -s; \
            exit 1; \
          fi
      - run: npm run test
      - run: npm run lint
      - run: npm run build
