name: preview-deploy

on:
  push:
    branches:
      - preview

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: make
        env:
          NAM: mh
          ENV: preview
          REF: ${{ github.sha }}
          PRE: preview
          TITLE: 'Minhajul Haq'
          DESCRIPTION: 'Minhajul Haq - Agama Islam dan Bahasa Arab'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: |
          docker stack config -c deployments/preview/stack.yaml > deployments/preview.stack.yaml
          sed -i '1d' deployments/preview.stack.yaml
        env:
          IMAGE: ttl.sh/mh-preview-khutwah-id-${{ github.sha }}:1h

      # TODO(dio): Add check to the required secrets.

      - uses: dio/stack-deploy-action@752338c6ac902a95dee2ebce5b25e4f1ba4a3b3c # master@02-01-2025
        with:
          name: preview-khutwah-id
          file: deployments/preview.stack.yaml
          host: preview.khutwah.id
          user: deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}
