name: Daily Draft Sabaq Automation

on:
  schedule:
    - cron: '0 14 * * *' # 9 PM Jakarta Time (UTC+7)
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  gen-draft-sabaq:
    runs-on: ubuntu-latest

    steps:
      - name: Send API Request with Retries
        run: |
          for i in {1..3}; do
            if curl -X GET "https://mtmh-staging.khutwah.id/api/v1/activities/automation" \
              --fail \
              --silent \
              --show-error; then
              echo "Request succeeded.";
              break;
            else
              echo "Attempt $i failed. Retrying...";
              sleep 5;
            fi
          done

          if [ $i -eq 3 ]; then
            echo "All retry attempts failed.";
            exit 1;
          fi
